name: data-structure-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test packages
    runs-on: ubuntu-latest

    steps:
      - name: Setup action
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Install dependencies
        run: |
          go mod tidy
      
      - name: Run Test
        run: |
          go test -v -cover ./...